
//PRDUCTOS
@api_students = http://localhost:3000/students

### REQUEST PRODUCT
GET {{api_students}}

### ADD PRODUCT
POST {{api_students}}
Content-Type: application/json

     {
      "dni": 34988562,
      "name": "Armando",
      "surname": "Predes",
      "date_of_brith": "1991-09-15",
      "date_of_admission": "2022-07-01",
      "username": "paredes",
      "password": "12345"
     }


### REQUEST PRODUCT BY CODE
GET {{api_students}}/34988562

### COUNT TOTAL PRODUCT
POST {{api_students}}/count

### DELETE PRODUCT
DELETE {{api_students}}/34988562

### UPDATE PRODUCT
PUT {{api_students}}/34988562
Content-Type: application/json

{
      "name": "Armandos",
      "surname": "Predes",
      "date_of_brith": "1991-09-15T00:00:00.000Z",
      "date_of_admission": "2022-07-01T00:00:00.000Z",
      "username": "paredes",
      "password": "12345"
}


