
//PRDUCTOS
@api_students = http://localhost:3000/users
GET {{api_students}}

### ADD PRODUCT
POST {{api_students}}
Content-Type: application/json

     {
      "dni": 37468845,
      "name": "Matiasss",
      "surname": "Escobario",
      "date_of_brith": "1992-08-16T00:00:00.000Z",
      "date_of_admission": "2022-03-01T00:00:00.000Z",
      "username": "escobar",
      "password": "123454",
      "teacher": false,
      "admin": false
     }


### REQUEST PRODUCT BY CODE
GET {{api_students}}/dni/27468845

### COUNT TOTAL PRODUCT
POST {{api_students}}/count

### DELETE PRODUCT
DELETE {{api_students}}/34988562

### UPDATE PRODUCT
PUT {{api_students}}/34988562
Content-Type: application/json

{
      "name": "Armandos",
      "surname": "Predes",
      "date_of_brith": "1991-09-15T00:00:00.000Z",
      "date_of_admission": "2022-07-01T00:00:00.000Z",
      "username": "paredes",
      "password": "12345"
}


